### ISSUE TITLE
KrakenD changes key order

### ISSUE THREAD

**Issue by tfluehmann** [devopsfaith/krakend-ce#172]
I am trying to simply proxy a JSON object which contains more other JSON objects through KrakenD. I want to keep the order of the JSON objects sent by the backend. KrakenD always changes the order to an alphabetical order.
I already tried to set the output_encoding and the encoding to no_op, but this does not seem to have an effect on the result. How can I keep the order of the backend?

```
version: 2
cache_ttl: 0s
timeout: 3000ms
extra_config:
  krakend-gologging:
    (...)
output_encoding: json
name: company
disable_rest: true
endpoints:
  - endpoint: /query
    querystring_params: ["*"]
    headers_to_pass: ["*"]
    method: GET
    timeout: 60s
    output_encoding: no_op
    backend:
      - url_pattern: /query
        encoding: no_op
        host:
          - localhost:3000
        disable_host_sanitize: false
```

# Example:
The backend returns an object like the following:
```
{
"agg" : 
  "b" : ["something"],
  "a" : ["something else"]
}
```
But KrakenD responds with an object like the this:
```
{
"agg" : 
  "a" : ["something else"],
  "b" : ["something"]
}
```
