### ISSUE TITLE
Krakend on Kubernetes: cannot parse port as int

### ISSUE THREAD

**Issue by albertob-altair** [devopsfaith/krakend-ce#260]
**Describe the bug**

Hi,

I've recently decided to move our Krakend v1.1.1 to v1.2.0. So I successfully built a Docker image according to the content of the repo https://github.com/devopsfaith/krakend-ce.git by running  `make krakend_docker_alpine` . Then I used this image to run a container inside Kubernetes using this `Deployment` and `Service`:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krakend2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: krakend2
        image: xyz.azurecr.io/path/to/krakend:1.2.0-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
        volumeMounts:
        - name: krakend2-json
          mountPath: /etc/krakend/krakend.json
          subPath: krakend.json
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: krakend2-json
        configMap:
          name: krakend2-json
```

```
apiVersion: v1
kind: Service
metadata:
  name: krakend-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8080
    protocol: TCP
  selector:
    app: krakend2
```

**Your configuration file**

I created a `configMap` with the following content (krakend.json):

```
{
    "version": 2,
    "name": "KrakenD on k8s",
    "port": 8080,
    "cache_ttl": "3600s",
    "timeout": "3s",
    "host": [ "https://jsonplaceholder.typicode.com" ],
    "endpoints": [
        {
            "endpoint": "/debug",
            "backend": [
                {
                    "host": [ "http://krakend-service:8000" ],
                    "url_pattern": "/__debug/debug"
                }
            ]
        },
        {
            "endpoint": "/combination/{id}",
            "backend": [
                {
                    "url_pattern": "/posts?userId={id}",
                    "is_collection": true,
                    "mapping": { "collection": "posts" }
                },
                {
                    "url_pattern": "/users/{id}",
                    "mapping": { "email": "personal_email" }
                }
            ]
        },
        {
          "endpoint": "/splash",
          "backend": [
            {
              "host": [ "http://fake_api:8080" ],
              "url_pattern": "/shop/campaigns.json",
              "whitelist": [ "campaigns" ]
            },
            {
              "host": [ "http://fake_api:8080" ],
              "url_pattern": "/shop/products.json",
              "whitelist": [ "products" ]
            }
          ]
        }
    ]
}
```

**Commands used**
How did you start the software?
```
kubectl apply -f krakend-k8s.yaml
```

The above yaml contains the deployment, configmap and service previously shown.

**Expected behavior**

Krakend running container inside Kubernetes.

**Logs**

```
ERROR parsing the configuration file: '/etc/krakend/krakend.json': 1 error(s) decoding:

* cannot parse 'port' as int: strconv.ParseInt: parsing "tcp://10.51.4.129:8080": invalid syntax
```

**Additional context**

The curious think is that if I run Krakend v1.1.1 with the exact same deployment, service and configmap it runs fine.

At this point I have no clue about what could be wrong here. Any thoughts?
