### ISSUE TITLE
Docker with Flexible

### ISSUE THREAD

**Issue by IsaiasFilho** [devopsfaith/krakend-ce#268]
I'm trying to use Flexible with **Krakend v1.2.0** in Docker, but it always exits with code 1 and no output error/message 

Here is my **Dockerfile:**

```
FROM devopsfaith/krakend:1.2.0 as krakend

ARG ENVIRONMENT

ENV FC_ENABLE=1
ENV FC_SETTINGS="config/settings"
ENV FC_OUT="/tmp/out.json"

COPY config/krakend_$ENVIRONMENT.json krakend.json
COPY config/$ENVIRONMENT config/

COPY entrypoint.sh .
ENTRYPOINT ["bash", "entrypoint.sh" ]
```

**My entrypoint.sh**
```
#!/bin/sh

#DEBUG
krakend check -c /etc/krakend/krakend.json -d

krakend run -c /etc/krakend/krakend.json -d
```

**My krakend.json:**
```
{
  "version": 2,
  "name": "My Krakend Dev",
  "extra_config": {
    "github_com/devopsfaith/krakend-cors": {
      "allow_origins": [
        "*"
      ],
      "allow_methods": [
        "POST",
        "GET"
      ],
      "allow_headers": [
        "*"
      ]
    }
  },
  "timeout": "10s",
  "cache_ttl": "300s",
  "output_encoding": "no-op",
  "port": 8080,
  "read_timeout": "10s",
  "write_timeout": "10s",
  "read_header_timeout": "10s",
  "idle_timeout": "10s",
  "endpoints": [
    {{ range private_endpoints.endpoints }}
    {
      "endpoint": "{{ .endpoint }}",
      "method": "{{ .method }}",
      "backend": [
        {
          "url_pattern": "{{ .backend_url }}",
          "method": "{{ .method }}",
          "encoding": "no-op",
          "sd": "static",
          "disable_host_sanitize": true,
          "host": ["http://myhost.org"],
          "extra_config": {
            "github.com/devopsfaith/krakend-httpsecure": {
              "allowed_hosts": [
                "vpn.host.org"
              ]
            }
          }
        }
      ]
    },
    {{ end }}
  ]
}
```
**config/settings/private_endpoints.json**
```
{
  "endpoints": [
    {
      "endpoint": "/v1/endpoint01",
      "method": "GET",
      "backend_url": "/endpoint01"
    },

    {
      "endpoint": "/v1/endpoint01",
      "method": "POST",
      "backend_url": "/endpoint01"
    },

    {
      "endpoint": "/v1/endpoint02",
      "method": "POST",
      "backend_url": "/endpoint02"
    },
    ...
  ]
}

```

**And finally my docker-compose file**
```
version: '3.4'
services:
  krakend:
    build:
      context: .
      args:
        ENVIRONMENT: dev
    image: krakend
    container_name: krakend-local
    networks:
      mynetwork:
        ipv4_address: 123.123.123.123
    ports:
      - "8080:8080"
networks:
  mynetwork:
    external: true
```
I'm using "docker-compose up --build" to start my application.

When I delete the range function **"private_endpoints.endpoints"** of the **krakend.json** file it works, but when I keep it, I just receive the following output:
```
Creating krakend-local ... done
Attaching to krakend-local
krakend-local | Parsing configuration file: /etc/krakend/krakend.json
krakend-local exited with code 1
```
