### ISSUE TITLE
TLS 1.3 not supported

### ISSUE THREAD

**Issue by cboitel** [devopsfaith/krakend-ce#330]
**Describe the bug**

Configuring TLS versions to 1.3 (min or max) isn't taken in account and gateway falls back silently to TLS 1.2
Configuring TLS versions to anything leads to the same result

See https://www.krakend.io/docs/service-settings/tls/: TLS13 is listed 

**To Reproduce**

In latest krakend version using lura, set config to include:

```
tls:
  private_key: /xxxx/server.key
  public_key: /xxxx/server.crt
  min_version: TLS12
  max_version: TLS13
```

Krakend/lura ignores TLS13 without warning/error. Using a ssl tool, one can see that TLS 1.3 isn't enabled.

**Expected behavior**

A warning should raised during parsing if version asked isn't supported/valid and documentation should state list of versions supported.
If it is supported, one should be able to enable it.

**Logs**

We tracked down the issue within luraproject/lura/transport/http/server/server.go which does not reference TLS13 as a valid version usable in a config file;

**Additional context**

A lura issue was raised https://github.com/luraproject/lura/issues/506
