### ISSUE TITLE
Excessive memory consumption when using rate limit on endpoints 

### ISSUE THREAD

**Issue by cboitel** [devopsfaith/krakend-ce#332]
**Describe the bug**

We have a configuration file with 50 (services) * 5 (resources/service) * 6 (operations/resource) endpoints. We want to enable a rate limit on each endpoint.

Krakend-CE exceeds 4Gb memory consumption and crash at startup around the 24th service.

If we remove the rate limit declaration, krakend starts and uses up to 10% of our 4Gb RAM host even after some load has been processed.

**Your configuration file**
The content of your `krakend.json`. When using the flexible configuration option, the computed file can be generated using `FC_OUT=out.json`
```yaml
version: 2
port: 8000
timeout: 1s
...
endpoints:
# Endpoints for the Service service00
  # Endpoints for the Resource art
  - endpoint: "/service00/arts"
    method: GET
    output_encoding: no-op
    headers_to_pass:
    - "*"
    extra_config:
      github.com/devopsfaith/krakend-ratelimit/juju/router:
        maxRate: 10
        clientMaxRate: 6
        strategy: "header"
        key: "Authorization"
    backend:
    - url_pattern: "/service00/arts"
      encoding: no-op
      host:
      - "https://service00:8000"
  - endpoint: "/service00/arts"
    method: POST
    output_encoding: no-op
    headers_to_pass:
    - "*"
    extra_config:
      github.com/devopsfaith/krakend-ratelimit/juju/router:
        maxRate: 10
        clientMaxRate: 6
        strategy: "header"
        key: "Authorization"
    backend:
    - url_pattern: "/service00/arts"
      encoding: no-op
      host:
      - "https://service00:8000"
  - endpoint: "/service00/arts/{id}"
    method: GET
    output_encoding: no-op
    headers_to_pass:
    - "*"
    extra_config:
      github.com/devopsfaith/krakend-ratelimit/juju/router:
        maxRate: 10
        clientMaxRate: 6
        strategy: "header"
        key: "Authorization"
    backend:
    - url_pattern: "/service00/arts/{id}"
      encoding: no-op
      host:
      - "https://service00:8000"
  - endpoint: "/service00/arts/{id}"
    method: PUT
    output_encoding: no-op
    headers_to_pass:
    - "*"
    extra_config:
      github.com/devopsfaith/krakend-ratelimit/juju/router:
        maxRate: 10
        clientMaxRate: 6
        strategy: "header"
        key: "Authorization"
    backend:
    - url_pattern: "/service00/arts/{id}"
      encoding: no-op
      host:
      - "https://service00:8000"
  - endpoint: "/service00/arts/{id}"
    method: DELETE
    output_encoding: no-op
    headers_to_pass:
    - "*"
    extra_config:
      github.com/devopsfaith/krakend-ratelimit/juju/router:
        maxRate: 10
        clientMaxRate: 6
        strategy: "header"
        key: "Authorization"
    backend:
    - url_pattern: "/service00/arts/{id}"
      encoding: no-op
      host:
      - "https://service00:8000"
  - endpoint: "/service00/arts/{id}"
    method: PATCH
    output_encoding: no-op
    headers_to_pass:
    - "*"
    extra_config:
      github.com/devopsfaith/krakend-ratelimit/juju/router:
        maxRate: 10
        clientMaxRate: 6
        strategy: "header"
        key: "Authorization"
    backend:
    - url_pattern: "/service00/arts/{id}"
      encoding: no-op
      host:
      - "https://service00:8000"
....
```
> i provided only sample conf for one ressource (art) on one service (service00). 

**Commands used**
Classic docker run -c /etc/krakend/config/krakend.yml

**Expected behavior**
We should be able to configure Krakend so it uses no more than 10/15% of our 4Gb machine

**Logs**
No error reported since OS deberately kills krakend for it is consuming too much memory.
 
**Additional context**
Also raised an issue in [krakend-limit](https://github.com/devopsfaith/krakend-ratelimit/issues/19)
