### ISSUE TITLE
No-op endpoint does not forward query params automatically?

### ISSUE THREAD

**Issue by EthanML** [devopsfaith/krakend-ce#364]
**Describe what are you trying to do**
Use no-op proxy endpoints.

**Your configuration file**

```json
{
      "endpoint": "/test/{route}/{params}/{work}/{correctly}",
      "output_encoding": "no-op",
      "backend": [
        {
          "url_pattern": "/test/{route}/{params}/{work}/{correctly}",
          "host": "{{ env "SERVICE_HOST_TEST" }}",
          "encoding": "no-op"
        }
      ]
    },
```

**Commands used**

Via the krakend docker image (dev/watcher version):

```
version: "3"
services:
  service-slice-gateway:
    image: devopsfaith/krakend:config-watcher
    environment:
      # KrakenD vars
      - FC_ENABLE=1 
      - FC_SETTINGS=config/settings
      - FC_PARTIALS=config/partials 
      - FC_TEMPLATES=config/templates 
      - FC_OUT=debug_config.json 
      - KRAKEND_CONFIG=config/krakend.json
      - SERVICE_HOST_TEST=${SERVICE_HOST_TEST:-http://example}

    ports:
      - "2000:8080"
    volumes:
      - .:/etc/krakend
    working_dir: /etc/krakend
```

--------------

When running a no-op endpoint, my experience has been that query parameters sent to the endpoint are _not_ automatically passed to the backend. They seem to have to be specified in the `querystring_params` config.

In the [no-op docs](https://www.krakend.io/docs/endpoints/no-op/) it states the following under "Key Concepts":

> The KrakenD endpoint works just like a regular proxy

> Headers passing to the backend still need to be declared under headers_to_pass, as they hit the router layer first.

With no mention of query params or anything else that might need to be manually specified, I naturally assumed they would be passed to the backend automatically. Is this not intended to be the case? If so, I think this should probably be stated in these docs alongside the point about headers.

Thanks
