### ISSUE TITLE
dns inside of "jwk_url"

### ISSUE THREAD

**Issue by Pythonov** [devopsfaith/krakend-ce#469]
Hi! Could you help to solve this problem?

**Describe the bug**
Trying to use container name of keycloak like address in jwk_url, but it does not work

**Your configuration file**

"extra_config": {
    "auth/validator": {
      "operation_debug": true,
      "sd": "dns",
      "alg": "RS256",
      "jwk_url": "keycloak:8080/auth/realms/master/protocol/openid-connect/certs",
      "disable_jwk_security": true
    }
}

```
**Commands used**
docker-compose. 

Krakend part:
  krakend:
    image: devopsfaith/krakend
    container_name: krakend
    hostname: krakend
    ports:
      - "9090:9090"
    volumes:
      - ./krakend_config:/etc/krakend/
    environment:
      FC_ENABLE: 1
      FC_TEMPLATES: /etc/krakend
    restart: on-failure

    command: [ "run", "-d", "-c", "/etc/krakend/minio.json" ]
```

**Expected behavior**
It works with dns

**Logs**
Getting this error:
krakend     | 2022/04/06 13:00:19 KRAKEND ERROR: [ENDPOINT: /tusp1/1080/:addr][JWTValidator] Unable to validate the token: Get "keycloak:8080/auth/realms/master/protocol/openid-connect/certs": unsupported protocol scheme "keycloak"
